language: php

php:
  - 5.5
  - 5.4
  - 5.3

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --no-interaction

script:
  - php vendor/bin/phpunit -c phpunit.xml.dist
